services:
  workspace:
    build: .
    # platform: linux/amd64
    tty: true
    restart: always
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes: 
      - ./:/var/app
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
